# Generated by Django 4.2.16 on 2025-01-19 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(blank=True, max_length=255, null=True)),
                ('service', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_date', models.DateField(default=datetime.datetime.today)),
                ('start_time', models.TimeField()),
                ('booked_slots', models.IntegerField(default=1)),
                ('paid', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_today', models.DateField(default=datetime.datetime.today)),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('slot_duration', models.IntegerField(default=20)),
                ('holiday', models.BooleanField(default=False)),
            ],
        ),
    ]
