# Generated by Django 4.2.16 on 2024-10-01 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_Date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
