# Generated by Django 4.2.16 on 2024-10-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_slots',
            field=models.IntegerField(default=1),
        ),
    ]
