# Generated by Django 4.2.16 on 2024-10-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_booked_slots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_Date',
            new_name='booking_date',
        ),
    ]
