# Generated by Django 4.2.16 on 2025-01-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_rename_booking_date_booking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
