# Generated by Django 4.2.16 on 2025-01-10 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_updated_at_alter_booking_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='finish_time',
        ),
    ]
